version: '3.8'

services:
  benben-mysql:
    image: mysql:5.7.35
    #Create a new user if using MySQL 8 - not currently functional
    #image: mysql:latest
    restart: always
    volumes:
      - .:/sqlsetup
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: Ou666Pfme4205oAM6m6S68688lqy4PQfxlYFlCnmPzyyzaloZ5Zw=
    #Create a new user if using MySQL 8 - not currently functional
    #command: mysql -u root -pOu666Pfme4205oAM6m6S68688lqy4PQfxlYFlCnmPzyyzaloZ5Zw= -e "CREATE USER 'new_user'@'%' IDENTIFIED WITH mysql_native_password BY 'Ou666Pfme4205oAM6m6S68688lqy4PQfxlYFlCnmPzyyzaloZ5Zw=';GRANT USAGE ON *.* TO 'new_user'@'%';ALTER USER 'new_user'@'%' REQUIRE NONE WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;GRANT ALL PRIVILEGES ON new_user.* TO 'new_user'@'%';FLUSH PRIVILEGES;"
  benben-phpmyadmin:
    image: phpmyadmin
    restart: always
    depends_on:
      - "benben-mysql"
    ports:
      - 8080:80
    environment:
      - PMA_HOST=benben-mysql
      - PMA_ARBITRARY=1
  benben:
    image: benben
    restart: always
    depends_on:
      - "benben-mysql"
    ports:
      - 3000:3000